---
- hosts: all
  user: root
  tasks:
  - name: install yum packages
    yum: name={{ item }}
    with_items:
      - git
      - mysql
      - nmap
      - traceroute

  - name: install update_keys.sh
    copy: mode=0754 src=files/update_keys.sh dest=/root/update_keys.sh

  - name: create cron job
    cron: minute="*/5" name="update_keys.sh" job="/bin/bash /root/update_keys.sh"